// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clear_grant.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearGrant = `-- name: ClearGrant :execrows
UPDATE principal SET grant_hash = NULL WHERE id = $1 AND grant_hash = $2
`

type ClearGrantParams struct {
	ID        pgtype.UUID
	GrantHash []byte
}

func (q *Queries) ClearGrant(ctx context.Context, arg ClearGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearGrant, arg.ID, arg.GrantHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
