// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_identity.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM principal WHERE id = $1
`

func (q *Queries) DeleteIdentity(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
