// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_grant_hash.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrantHash = `-- name: GetGrantHash :one
SELECT grant_hash FROM principal WHERE id = $1
`

func (q *Queries) GetGrantHash(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGrantHash, id)
	var grant_hash []byte
	err := row.Scan(&grant_hash)
	return grant_hash, err
}
