// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_identity.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentity = `-- name: GetIdentity :one
SELECT id, name, display_name, creation_date, last_authenticated_date, grant_hash
  FROM principal
 WHERE id = $1
`

func (q *Queries) GetIdentity(ctx context.Context, id pgtype.UUID) (Principal, error) {
	row := q.db.QueryRow(ctx, getIdentity, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.CreationDate,
		&i.LastAuthenticatedDate,
		&i.GrantHash,
	)
	return i, err
}
