// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Principal struct {
	ID                    pgtype.UUID
	Name                  string
	DisplayName           string
	CreationDate          int64
	LastAuthenticatedDate int64
	GrantHash             []byte
}
